version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=3000

    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/logs:/var/lib/zookeeper/logs

  kafka_broker_1:
    container_name: kafka_broker_1
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      - KAFKA_BROKER_ID=1
      # Name of zookeeper where broker should connect
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # Mapping between listener names and the security protocols they use
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # INTERNAL: inside and EXTERNAL: outside
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka_broker_1:9092,EXTERNAL://localhost:9093
      # Kafka listeners URL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      # Communication between different Kafka brokers in a cluster
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # For logger
      - KAFKA_LOG4J_LOGGERS="kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      # Replication Topic on the all brokers(no of brokers -1)
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    volumes:
      - ./kafka/data:/var/lib/kafka/data

    # restart: always
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka_broker_1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=zookeeper:2181
      - DYNAMIC_CONFIG_ENABLED=true
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=pass

    depends_on:
      - kafka_broker_1
    restart: always
